@startuml
left to right direction 



rectangle Usuario{
actor Proponente as p
actor Aliado as a
package "Admin"{
actor "Direccion de extension" as de
actor "Consejo de Facultad" as cf
actor "Comision de Extension" as ce
actor "Coordinacion de Extension" as co
}
}

rectangle Sistema{
usecase Registro as UC1
usecase "Inicio de sesion" as UC2
usecase "Gestionar perfil" as UC3
usecase "Proponer curso" as UC4
usecase "Presentar informacion del curso" as UC5
usecase "Validar curso" as UC6
usecase "Rechazar curso" as UC7
usecase "Aprobar curso" as UC8
usecase "Clasificar curso" as UC9

}

Usuario --> UC1
Usuario --> UC2
Usuario --> UC3
p --> UC4
p --> UC5
Admin --> UC6
Admin --> UC7
Admin --> UC8
Admin --> UC9




@enduml
